### ISSUE TITLE
Creating a bridge for atom with elixir-ls and atom-ide: ide-elixir?

### ISSUE THREAD

**Issue by agustif** [JakeBecker/elixir-ls#10]
https://blog.atom.io/2017/09/12/announcing-atom-ide.html

Reading these news, I remembered your project, do you use Atom yourself, any plans on making this happen?

**Comment by JakeBecker** [comment]
Hi,

Sorry for the wait in getting back to you. I don't use Atom myself, but I took a quick look. The Atom IDE package is based on v2 of the Language Server Protocol, and ElixirLS uses v3. They're pretty similar though, it may be possible to make it compatible with v2. Also, it doesn't look like it supports the VS Code Debug Protocol, which means that debugger integration won't be possible.

I'm going to take a quick stab at an Atom plugin. I'll report back here if I make any progress.

**Comment by JakeBecker** [comment]
It basically works! Repo here: https://github.com/JakeBecker/ide-elixir

It's got some issues. Snippets in auto-complete don't work, so I think I need to add some indication to the `clientCapabilities` and look for that in the server. Also, the Atom client doesn't handle the `window/logMessage` or `window/showMessage` notifications from the server, which makes it harder to diagnose issues. I don't want to publish quite yet until I've worked out more of the bugs in ElixirLS, since I expect bug reports from Atom will be lacking in relevant information because of this.

Feel free to try it out though!

**Comment by agustif** [comment]
Thanks, this looks cool! Right now working on JS, but will try soon!

**Comment by ontofractal** [comment]
@JakeBecker Great to see that you're working on a atom-ide extension for elixirLS!

**Comment by JakeBecker** [comment]
The main blocker right now is this issue: https://github.com/atom/atom-languageclient/issues/130

Once there's a fix for that, I'll release the plugin and close this issue.

**Comment by JakeBecker** [comment]
I've just released the Atom IDE extension. Blog post here: https://medium.com/@JakeBeckerCode/announcing-ide-elixir-an-elixirls-plugin-for-atom-ide-379fb71f7b7f

Thanks for the encouragement, everyone! 👍
