### ISSUE TITLE
Crash in elixir_sense

### ISSUE THREAD

**Issue by lukaszsamson** [JakeBecker/elixir-ls#104]
## Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Operating system: OSX 10.13.6
* Client (editor or IDE): 1.25.1
* Plugin: 0.2.22

### Crash report template

This happens all the time when editing files (especially when there are syntax errors). Not sure if this is elixir_sense error or elixir-ls misuse of elixir_sense api.

```
[Error - 09:47:37] Request textDocument/hover failed.
  Message: an exception was raised:
    ** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.extract_spec_ast_parts/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:282: ElixirSense.Core.Introspection.extract_spec_ast_parts({:t, [], [{:value, 41, nil}]})
        (elixir_sense) lib/elixir_sense/core/introspection.ex:226: ElixirSense.Core.Introspection.format_spec_ast/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:208: ElixirSense.Core.Introspection.format_type/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:181: anonymous fn/2 in ElixirSense.Core.Introspection.get_types_with_docs/1
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir_sense) lib/elixir_sense/core/introspection.ex:128: ElixirSense.Core.Introspection.get_types_md/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:78: ElixirSense.Core.Introspection.get_all_docs/1
        (elixir_sense) lib/elixir_sense/providers/docs.ex:13: ElixirSense.Providers.Docs.all/4
        (elixir_sense) lib/elixir_sense.ex:50: ElixirSense.docs/3
        (language_server) lib/language_server/providers/hover.ex:7: ElixirLS.LanguageServer.Providers.Hover.hover/3
        (language_server) lib/language_server/server.ex:403: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 
```
msaraiva/elixir_sense#32

**Comment by lukaszsamson** [comment]
https://github.com/msaraiva/elixir_sense/issues/33

**Comment by JakeBecker** [comment]
Thank you for your issue and PR! The crash originates in Elixir Sense and should probably get fixed there.

As long as the exception only happens in an asynchronous provider and it won't crash the main ElixirLS server process, I've been adhering to the "let it fail" school of thought for error handling. Since there's no easy way to actually return a successful response, there's no real need to rescue these exceptions since we'd just end up having to return an error or an empty response to the client anyway. Only real downside is that it pollutes the logs with exceptions that don't really matter.

**Comment by lukaszsamson** [comment]
@JakeBecker msaraiva/elixir_sense#32 and msaraiva/elixir_sense#33 are now fixed on elixir_sense master
