### ISSUE TITLE
Ability to prefix all `mix` commands? 

### ISSUE THREAD

**Issue by florish** [JakeBecker/elixir-ls#122]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.3 / Erlang/OTP 21
* Operating system: macOS / Docker
* Client (editor or IDE): VSCode

This is not really a bug, more a question. If this isn't the place for that, please let me know.

I've just started working on an Elixir project using Docker and docker-compose. As such, all `mix` tasks should ideally run inside a `docker-compose` service, as that's where the correct Elixir version runs.

Is there any configuration setting to prefix all `mix` commands? For example:

```
$ mix deps.get
```

Should in my case always be:

```
$ docker-compose run SERVICE_NAME mix deps.get
```

The `mix deps.get` task is also a specific case where I ran into trouble with changes in `mix.lock` between Elixir versions. Reason: on my local machine I have a slightly different Elixir version than in the Docker container.

Hope I just missed a configuration setting...

And last but not least: thanks for all the work on this project, really helpful to have all these tools available!

**Comment by JakeBecker** [comment]
This is unfortunately not really doable because ElixirLS doesn't actually run any Mix commands via a shell, it just calls the functions directly from within the VM. I've gotten a number of requests for better control over how the server is launched, though, and so I do plan to make the server launch command configurable in future versions which should make it possible to run the server within a container.

Going to close this as there are other issues already about improving container support.

**Comment by florish** [comment]
@JakeBecker Thanks for getting back on this. Sounds like the other plans will indeed resolve this issue.

For future reference: could you list the specific issues and/or pull requests you're referring to?
