### ISSUE TITLE
Add "Reload Module" command...?

### ISSUE THREAD

**Issue by mattbaker** [JakeBecker/elixir-ls#140]
Now, I'm not saying this is a _good_ idea, but I want to throw it out there.

I often find myself recompiling modules in IEX as I make changes with [`IEx.Helpers.r/1`](https://hexdocs.pm/iex/IEx.Helpers.html#r/1). 

Yesterday I watched in envy as my friend, in his editor, triggered the reloading of a clojure namespace in his REPL, and thought "why can't I do that in Elixir?"

And, technically, we _could_. With a (matching) cookie and node name set elixir-ls could use the `:rpc` module to tell another node (presumably your application/iex session) to reload a module. It would require configuration, since the cookie would need to be provided, and presumably the node name as well.

@JakeBecker — I did a little experimenting and I actually think this is doable. It's also some mad science, and I will not be offended if your response is "no, this is absurd". 

But, if you are curious, I could hack on it some more*.

As always, thank you for this lovely extension, we use it daily.

<3,
Matt

* standard caveat of "no promises, work is hecka busy" applies

**Comment by axelson** [comment]
This is even easier to accomplish with `IEx.Helpers.nl/2`. That'll take care of all the heavy lifting (although we may have to ensure that the environments are similar enough).

**Comment by JakeBecker** [comment]
Hi Matt!

I don't think it's crazy, but my initial gut feeling is that it's not worth the complexity it'd introduce. Right now, we override the build directory to `.elixir_ls/build` (instead of `_build`) to avoid risking interference with other build tools. This was motivated in particular by Phoenix live reload, which relies on being able to detect changed source files and recompile them itself. Also, sometimes people run VS Code with an environment that has a different version of Elixir or Erlang than they use on the CLI. Occasionally, there have also been issues with ElixirLS's embedded version of Jason interfering with the project's preferred version. In general, it's been easier to keep the build output of ElixirLS and other tools completely separate, even though it means they each have to do their own compilations, so I'm wary of doing anything that makes ElixirLS the source of truth for CLI tools like iex.

Also, I believe that by default, iex runs without connecting to epmd, so there's no way to make ElixirLS connect to it automatically unless the user passes CLI options to iex to give it a node name.

Maybe a simpler way to accomplish something like this would be to write a library that uses a filesystem watcher like [this](https://github.com/falood/file_system) or [this](https://github.com/whitfin/sentix) and calls the IEx recompile helper when source files change. You could package it as a mix archive, and then users would just have to do `mix archive.install` and it'd be available in any IEx session.

I appreciate the thought, and I'm sorry to be discouraging. And I'm glad you're finding ElixirLS useful!

**Comment by mattbaker** [comment]
> In general, it's been easier to keep the build output of ElixirLS and other tools completely separate, even though it means they each have to do their own compilations, so I'm wary of doing anything that makes ElixirLS the source of truth for CLI tools like iex.

Agreed, I've _really_ appreciated Elixir LS's isolation in that regard, I think it's a big strength. The function @axelson mentioned is cool, but I think what I was suggesting maintains the isolation: 

```
:rpc.call(node_host, IEx.Helpers, :r, [module])
```

It's just one node sending a message to another, essentially we're typing "r(FooBar)" for the user.

> Also, I believe that by default, iex runs without connecting to epmd, so there's no way to make ElixirLS connect to it automatically unless the user passes CLI options to iex to give it a node name.

Indeed, it would take config. The person has to start iex with a cookie and `sname` flag. In my branch (again, just experimenting) I added two settings for the vscode extension, a host to connect to and a cookie.

I'll push up my branch so you can take a look just for kicks, but I understand not wanting to add complexity to the language server. 

In fact, it's such a simple thing (boot an elixir node and send a message to another node) that I think I may try to just encapsulate it in its own extension! :) I thought about something watching the filesystem, but I actually want to be able to selectively choose when to reload something.
