### ISSUE TITLE
nvim support is very limited

### ISSUE THREAD

**Issue by alexcastano** [JakeBecker/elixir-ls#17]
Hello,

I'm using this nvim plugin: https://github.com/autozimu/LanguageClient-neovim

It works with rust or javascript language servers.

There are some commands that work correctly like the formatting.
On the other hand, `:call LanguageClient_textDocument_rename()` or `:call LanguageClient_textDocument_documentSymbol()` don't work.

Some errors from `/tmp/LanguageClient.log`:

```
18:33:47 ERROR   [MainThread] {'jsonrpc': '2.0', 'id': 8, 'error': {'message': 'Invalid Request', 'code': -32600}}
18:34:48 ERROR   [MainThread] {'jsonrpc': '2.0', 'id': 9, 'error': {'message': 'Invalid Request', 'code': -32600}}
18:35:30 WARNING [MainThread] Unknown parameter key: newName
18:35:31 ERROR   [MainThread] {'jsonrpc': '2.0', 'id': 10, 'error': {'message': 'Invalid Request', 'code': -32600}}
18:35:35 WARNING [MainThread] Unknown parameter key: newName
18:35:35 ERROR   [MainThread] {'jsonrpc': '2.0', 'id': 11, 'error': {'message': 'Invalid Request', 'code': -32600}}
```
If you need help to give support to (n)vim I'll do my best to help you!

**Comment by JakeBecker** [comment]
These aren't specific to nvim -- those requests are just not handled yet in ElixirLS. The error message isn't very informative, so that could probably be improved. The server informs the client of its capabilities in response to the `initialize` request, and I guess nvim doesn't check that before deciding what requests to send. The rough list of features currently supported is in the README here: https://github.com/JakeBecker/elixir-ls#features

I'm going to close this issue, since it's not really about nvim. I'll make new issues for the currently unsupported request types.
