### ISSUE TITLE
Improve error range highlights for mismatched terminators

### ISSUE THREAD

**Issue by alexcastano** [JakeBecker/elixir-ls#23]
If a `do` is not properly close with an `end` it returns an error in the last `end` + 1. If the last `end` is in the last line --usually it is-- this makes some editors cannot show the error: https://github.com/autozimu/LanguageClient-neovim/issues/170#issuecomment-344233403

**Comment by JakeBecker** [comment]
👍  on this issue, finding mismatched terminators can be a real pain. I think it'd be good to highlight the full range starting from the opening terminator.

The place to make this change, ideally, would be in Elixir's compiler, since ElixirLS relies on the compiler's diagnostics for error positions.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
