### ISSUE TITLE
Monorepo: "No mixfile found in project root."

### ISSUE THREAD

**Issue by phyllisstein** [JakeBecker/elixir-ls#29]
Hey there! Thanks for creating this module, it's made for a great addition to my Elixir workflow in Atom. I have one small question or quibble, though. It's kind of an edge case, but in at least one project I'm working on, I've wound up placing a Node.js app alongside the Elixir app for simpler monorepo-style development. The problem is that then my Elixir project and its `mix.exs` are in a subdirectory of my Atom project, and ElixirLS fails to find them:

![screenshot](https://user-images.githubusercontent.com/2207980/33171800-af16c3d8-d01b-11e7-9f88-3b32a1bfc2a6.png)

I've tried setting the `MIX_EXS` environment variable to the absolute path of the subfolder's `mix.exs`, only to get this friendly message:

![screenshot 1](https://user-images.githubusercontent.com/2207980/33172675-17f0a5ce-d01f-11e7-8a02-45d2e8ecab14.png)

If you have any thoughts or suggestions I'd be grateful to hear them! My Elixir-fu is still a little weak but I'm happy to do anything I can to help with a PR if you can suggest a starting-point. Thanks so much, in advance, for your help.

**Comment by JakeBecker** [comment]
Apologies for the wait in getting back to you. Recent versions of ElixirLS have a setting `elixirLS.projectDir` which let you set the root of your Elixir project to a subdirectory of your workspace root.

Inexplicably, however, Atom does not allow you to set per-project settings: https://github.com/atom/atom/issues/5168 .  There are third party plugins for this, but the most popular one https://github.com/danielbrodin/atom-project-manager doesn't seem to work with the `atom-languageclient` language server client plugin.

It's really weird that Atom has been around so long and is still missing some basic stuff like this. My recommendation, unfortunately, is to just open another editor at your Elixir project's subdirectory, or try VS Code instead since you can just set the `elixirLS.projectDir` setting in your project's `.vscode/settings.json`.

**Comment by phyllisstein** [comment]
Thanks! No worries about the delay; I appreciate the legwork, even if it turns out that Atom is just not going to accommodate me here. Serves me right for being too lazy to split up my projects properly. 😬
