### ISSUE TITLE
Skipping build on Windows

### ISSUE THREAD

**Issue by andyeskridge** [JakeBecker/elixir-ls#34]
I am trying out the VSCode extension and am running into an issue on Windows. This comparison below is failing:

https://github.com/JakeBecker/elixir-ls/blob/846c3b3d8392e6e544301d30baf6586e748e34fd/apps/language_server/lib/language_server/build.ex#L6

`root_path` does not contain the drive letter, while `File.cwd!()` does contain the drive letter. Here is the output I receive in VSCode:

`Skipping build because cwd changed from Development/islands_engine to c:/Development/islands_engine`

Looking through the documentation, maybe `Path.expand/1` would work better than `Path.absname/1`? The only difference is that `expand/1` will expand out `..`, `.`, and `~`

**Comment by JakeBecker** [comment]
Just released v0.2.10 with the fix.

**Comment by vheathen** [comment]
I've got the same problem but with WSL. I'm able to start ElixirLS inside WSL but then I get a message like this:

Skipping build because cwd changed from /c:/cloud/Documents/Projects/some_project to /mnt/c/cloud/Documents/Projects/some_project. I believe this can be the reason why Go to definition doesn't work (does it?).

Dialyzer builds works fine though.

Don't know how to deal with it yet.
