### ISSUE TITLE
Do not complete after spaces or commas

### ISSUE THREAD

**Issue by ejpcmac** [JakeBecker/elixir-ls#38]
I am not sure if this is a bug from Atom `ide-elixir` or `elixir-ls`, so I post it here.

When finishing a line with a comma, like in a list or in a `with` statement, the autocomplete view appears. So typing `Enter` does not give me a newline, but completes with the first thing of the list.

I am used to `atom-elixir`’s behaviour regarding the completion, which I think is more natural.

I’ve seen that Atom does not yet support snippets. Is this the cause of `def<tab>` not working for creating new functions?

How could I help to get this better? (I’ve never written anything for Atom, but I could give it a try)

**Comment by JakeBecker** [comment]
Huh. I wasn't able to reproduce it in VS Code, so likely some strangeness with Atom IDE. The autocompletion characters are specified here: https://github.com/JakeBecker/elixir-ls/blob/master/apps/language_server/lib/language_server/server.ex#L398 .  `atom-languageclient` looks like it is meant to support this option too: https://github.com/atom/atom-languageclient/blob/a6a620694b49fe1c2cd51a7d9b698c505ea08416/lib/languageclient.js#L741

Autocomplete should only trigger automatically after a `.` character, so `def<tab>` should not autocomplete. But also, last I checked, `atom-languageclient` didn't support snippets, so triggering it manually wouldn't work either. For now, these snippets are built into the VS Code plugin, rather than the language server. Unfortunately, the whole auto complete provider in ElixirLS is a bit of a mess which I hope to clean up eventually.

Because I can't reproduce your issue in VS Code, you may need to file it on the https://github.com/atom/atom-languageclient repo instead.

**Comment by ejpcmac** [comment]
@JakeBecker I’ll take a look on this tomorrow. I close the issue here.
