### ISSUE TITLE
Support textDocument/rangeFormatting

### ISSUE THREAD

**Issue by robgrant** [JakeBecker/elixir-ls#45]
Documentation: https://microsoft.github.io/language-server-protocol/specification#textDocument_rangeFormatting

I may take a stab at implementing this myself but I wanted to first confirm that there isn't a reason it's not yet implemented.

**Comment by JakeBecker** [comment]
The main reason is that Elixir's formatter requires its input to be syntactically correct, so any range you try to format would have to be correct Elixir code on its own. I guess you'd also need to indent it based on the indentation of the first line in the range and adjust the target line-length to compensate. Could be done, though I'm curious when you'd want to use this over formatting the entire document.

**Comment by OvermindDL1** [comment]
> Could be done, though I'm curious when you'd want to use this over formatting the entire document.

Because formatting the entire document can utterly *break* readability in many ways, so many of us like to format it on a chunk by chunk basis.  Currently I'm doing that via the elixir formatter extension in atom where I can just select a chunk of text and hit `Ctrl+Alt+f` and it gets formatted, but it also get's fully left aligned, which is a bit irritating...  ^.^;

**Comment by irrigator** [comment]
> Because formatting the entire document can utterly break readability in many ways

Is that a problem with the formatter?

I have used Prettier for JavaScript and just started to use Elixir's formatter. When using Prettier I always want to format the entire document and it causes no problems. Anything I'm missing?

**Comment by OvermindDL1** [comment]
> Is that a problem with the formatter?

It's not a 'bug' in the formatter, but rather a design fault in the formatter.  Say you have a matrix of numbers in a list or tuple arranged in a mathematical way (as was one of my cases it broke), nicely readable and made mathematical sense, then the formatter decides it just wants to format it all so each number ends up on it's own line, breaking it up from 18 lines to 258 lines while losing all semantic information about how the numbers relate.

> I have used Prettier for JavaScript and just started to use Elixir's formatter. When using Prettier I always want to format the entire document and it causes no problems. Anything I'm missing?

Same thing in javascript, formatters in it can entirely lose semantic information.  Just because someone is writing in Elixir or Javascript doesn't mean that there are not subdomains inside those like math or parsing or so of which should be formatted differently from the main language, and this is where formatters fail *hard*.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
