### ISSUE TITLE
Debugging during compilation

### ISSUE THREAD

**Issue by webdeb** [JakeBecker/elixir-ls#53]
Is it possible to perform debugging while compiling?
Could be useful to debug macros.

In VSCode I've tried to add a compile task to the `launch.json` configuration:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "mix_task",
      "name": "mix compile",
      "request": "launch",
      "task": "compile",
      "projectDir": "${workspaceRoot}",
      "requiredFiles": ["mix.exs"]
    },
    ...
}
```

However, it did not worked. Thats the output, when I tried to put a breakpoint inside the mix.exs file:

```
  use Mix.Project
  test = "afasdfs"
  quote do #  added breakpoint here
    IO.inspect(unquote(test))
  end
```

Thats the output:

```
** Invalid beam file or no abstract code: 'Elixir.Pipe.Umbrella.Mixfile'
16:39:17.483 [error] 'File operation error: eisdir. Target: /Users/bk/play/pipe. Function: get_file. Process: Elixir.ElixirLS.Debugger.Server.'
```

**Comment by JakeBecker** [comment]
You can only set breakpoints within functions in modules. Since you can only debug module functions anyway, you'd need to move any macro code you want to debug into a function. At that point, you're probably better off writing a test for that function and debugging that. Debugging already requires a lot of hacks, unfortunately, so I'm probably not going to attempt to make it support debugging compilation.
