### ISSUE TITLE
Extra `@`  on argument call when autocomplete happens

### ISSUE THREAD

**Issue by quolpr** [JakeBecker/elixir-ls#66]
#### Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.3 (compiled with OTP 19)
#### Operating system

macOS sierra 10.12.6
#### Client (editor or IDE):

VSCode 1.21.0

### Example
![screencast 2018-03-13 10-53-39](https://user-images.githubusercontent.com/7958527/37328982-04ff20aa-26ad-11e8-8d11-25249686870c.gif)

**Comment by JakeBecker** [comment]
It happens when adding text in snippets. I think VS Code may be sending the wrong cursor position when you're already inside a snippet.

Module attributes are a little tricky to autocomplete correctly because VS Code doesn't consider the "@" part of the word, so we have to check whether the "@" has been typed already or not and insert it only if it's not already there.

Btw, thanks for the video, it helps diagnose issues like this. What do you use to record those?

**Comment by JakeBecker** [comment]
Actually it happens if you're not inserting into a snippet, too. I likely done screwed up somewhere.

**Comment by JakeBecker** [comment]
Looks like it was an off-by-one bug when finding the prefix. Fixed it here: https://github.com/JakeBecker/elixir-ls/commit/79fd784e0412ffc3e9e5943d0554878d86326fed

The fix will be included in the next release 👍

**Comment by quolpr** [comment]
Great, thank you! I used monosnap to record the gif

**Comment by JakeBecker** [comment]
Just published v0.2.19 with the fix.
