### ISSUE TITLE
Expose over TCP

### ISSUE THREAD

**Issue by rawkode** [JakeBecker/elixir-ls#7]
Hi,

I'd like to use this, but I don't have Elixir installed; as everything runs in a container. If this was exposed over TCP, I believe I could get it to work.

Any thoughts on the complexity of this?

**Comment by tvjg** [comment]
@rawkode Did you ever find an alternative? I have a similar situation.

**Comment by rawkode** [comment]
Sorry @tvjg, I'm still waiting for this to be a thing; no word from @JakeBecker yet

**Comment by Trevoke** [comment]
I could also use this.

**Comment by JakeBecker** [comment]
At the moment, I don't have plans to implement this myself because it isn't necessary for the VS Code or Atom plugins I maintain, but I would accept PRs that implement it. Relevant sections of the code to look at include:

* [ElixirLS.Utils.PacketStream.stream/1](https://github.com/JakeBecker/elixir-ls/blob/master/apps/elixir_ls_utils/lib/packet_stream.ex). This is a utility to stream packets from stdin. We'd need a version of that to stream packets from TCP instead. The API for a tcp connection is a bit different from stdout but should be fairly straightforward using `:gen_tcp`.
* [ElixirLS.Utils.WireProtocol](https://github.com/JakeBecker/elixir-ls/blob/master/apps/elixir_ls_utils/lib/wire_protocol.ex). We use the `send/1` function to write packets to stdout. Should be fairly straightforward to write them to a tcp socket instead.
* [ElixirLS.LanguageServer.CLI](https://github.com/JakeBecker/elixir-ls/blob/master/apps/language_server/lib/language_server/cli.ex).  This is where execution starts when running the release, so we'd want to add CLI options for specifying TCP instead of stdio mode and the port number.

**Comment by ryansch** [comment]
I've got socat working with the following config (binary release unzipped in /srv):
```
CMD ["socat", "-d", "-d", "-d", "TCP4-LISTEN:7659,reuseaddr,fork", "EXEC:/srv/language_server.sh"]
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
