### ISSUE TITLE
Support outline view

### ISSUE THREAD

**Issue by LostKobrakai** [JakeBecker/elixir-ls#90]
Now as it's out of preview it would be nice to have the vscode outline view work with elixir files: https://code.visualstudio.com/updates/v1_25#_outline-view

**Comment by JakeBecker** [comment]
Interesting! I hadn't known about this feature. Should be doable.

cc @mattbaker, feel free to take a stab at it if you feel so inclined :)

**Comment by mattbaker** [comment]
I think the outline view just leverages the symbol provider that we added in #52 so we got it for free with the VSCode update. Looks like it's working to me...?

<img width="829" alt="screen shot 2018-07-11 at 12 26 48 pm" src="https://user-images.githubusercontent.com/55462/42595001-bb637d9e-8505-11e8-8417-c3db9a56c0eb.png">

**Comment by JakeBecker** [comment]
Hm, the documentation suggests that the API has changed:

> To get the most out of the new Outline view tree, extensions should modify their DocumentSymbolProviders to return DocumentSymbols. This is a new type added and tailored towards the needs of the outline tree.

However, I don't see this reflected in the Language Server Protocol spec: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

Once the spec is updated, I'll plan to make the changes so the outline view can be nested instead of flat.

**Comment by LostKobrakai** [comment]
I'd also really like to see the outline show tests in test files if that's possible.
